### PR TITLE
Fix: Connection strings and authentication source

### PR DESCRIPTION
**Pull request by exaby73**

### CODE REVIEW

**Comment by anthonyshew** [comment]
What's up, Ex! @exaby73 😍

Alrighty, so getting this done would be awesome and enable a truly isolated development environment. Unfortunately, I can't get it running correctly.

If I run the compose for the first time, it successfully runs mongo. However, any attempts after that show these error logs: 

```
mongo               | {"t":{"$date":"2022-01-22T05:07:27.159+00:00"},"s":"I",  "c":"NETWORK",  "id":4915701, "ctx":"thread1","msg":"Initialized wire specification","attr":{"spec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":13},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":13},"outgoing":{"minWireVersion":0,"maxWireVersion":13},"isInternalClient":true}}}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.159+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"thread1","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.161+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"thread1","msg":"No TransportLayer configured during NetworkInterface startup"}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.161+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"thread1","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.163+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"thread1","msg":"No TransportLayer configured during NetworkInterface startup"}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.163+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"thread1","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationDonorService","ns":"config.tenantMigrationDonors"}}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.163+00:00"},"s":"I",  "c":"REPL",     "id":5123008, "ctx":"thread1","msg":"Successfully registered PrimaryOnlyService","attr":{"service":"TenantMigrationRecipientService","ns":"config.tenantMigrationRecipients"}}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.163+00:00"},"s":"I",  "c":"CONTROL",  "id":5945603, "ctx":"thread1","msg":"Multi threading initialized"}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.163+00:00"},"s":"I",  "c":"CONTROL",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"c226ff9f1cf5"}}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.163+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"5.0.5","gitVersion":"d65fd89df3fc039b5c55933c0f71d647a54510ae","openSSLVersion":"OpenSSL 1.1.1f  31 Mar 2020","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2004","distarch":"x86_64","target_arch":"x86_64"}}}}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.163+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"20.04"}}}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.163+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"},"security":{"authorization":"enabled"}}}}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.167+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/data/db","storageEngine":"wiredTiger"}}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.170+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=480M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),builtin_extension_config=(zstd=(compression_level=6)),file_manager=(close_idle_time=600,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.422+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1642828047:422920][1:0x7f81739efc80], file:WiredTiger.wt, connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.455+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1642828047:455226][1:0x7f81739efc80], file:WiredTiger.wt, connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.484+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1642828047:483978][1:0x7f81739efc80], file:WiredTiger.wt, connection: __posix_open_file, 808: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.487+00:00"},"s":"W",  "c":"STORAGE",  "id":22347,   "ctx":"initandlisten","msg":"Failed to start up WiredTiger under any compatibility version. This may be due to an unsupported upgrade or downgrade."}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.487+00:00"},"s":"F",  "c":"STORAGE",  "id":28595,   "ctx":"initandlisten","msg":"Terminating.","attr":{"reason":"1: Operation not permitted"}}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.487+00:00"},"s":"F",  "c":"-",        "id":23091,   "ctx":"initandlisten","msg":"Fatal assertion","attr":{"msgid":28595,"file":"src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp","line":687}}
mongo               | {"t":{"$date":"2022-01-22T05:07:27.487+00:00"},"s":"F",  "c":"-",        "id":23092,   "ctx":"initandlisten","msg":"\n\n***aborting after fassert() failure\n\n"}
mongo exited with code 14
```

Note that because mongo isn't running, the front-end will not be able to build most of the pages of the site - namely, the ones that depend on data coming from mongo. That includes the home page, the Games page, the Channels pages...If you visit `/terms-of-use`, for instance, you will end see that the front-end is running.

I'll try to help as best I can with this but will lean on your knowledge because you seem pretty confident with it! 😊

**Comment by anthonyshew** [comment]
I made a new commit updating a few things to make sure we only use "admin" in dev mode. Commit dc60753...Not sure why this PR didn't update.

**Comment by exaby73** [comment]
I've added a separate volume for mongo. Reference [here](https://stackoverflow.com/questions/61147270/docker-compose-and-mongodb-failed-to-start-up-wiredtiger-under-any-compatibilit).

Can you try this and see if it works? Doesn't seem to be reproducible on UNIX based systems like mine (MacOS)

**Comment by anthonyshew** [comment]
@exaby73 Yes!!! The container works and I got the volumes going! I'll work on how I want the seeding to work and then we can have a sweet workflow for a local database.

YOU DA MAN!

**Comment by exaby73** [comment]
Glad it works :D

**Pull request merged**
